### PR TITLE
Update freedesktop-sdk to 21.08 (+ update packaged dependencies)

### PR DESCRIPTION
**Pull request by doraskayo**
Also update the packaged dependencies:
- libostree: v2021.5
- pygobject: 3.42
- pycairo: v1.20.1

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by doraskayo** [comment]
bot, build

**Comment by doraskayo** [comment]
bot, build

**Comment by doraskayo** [comment]
The build passed, but this likely needs some testing before merge. I'll keep the PR as draft until then.

**Comment by doraskayo** [comment]
bot, build

**Comment by doraskayo** [comment]
Seems to work fine based on my tests. Marking as ready for review.

**Pull request merged**
